# Generated by Django 6.0.2 on 2026-02-26 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_testblueprint_blueprintrule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blueprintrule',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], max_length=10),
        ),
    ]
