# Generated by Django 6.0.2 on 2026-03-02 18:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_attempt_test_result_test_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attempt',
            old_name='attempted_at',
            new_name='started_at',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='difficulty',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='question',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='selected_option',
        ),
        migrations.RemoveField(
            model_name='attempt',
            name='skill',
        ),
        migrations.AddField(
            model_name='attempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attempt',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='result',
            name='attempt',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='core.attempt'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('selected_option', models.CharField(max_length=5)),
                ('is_correct', models.BooleanField()),
                ('difficulty', models.CharField(max_length=10)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.attempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.question')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.skill')),
            ],
        ),
    ]
