# Generated by Django 6.0.2 on 2026-03-03 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_rename_attempted_at_attempt_started_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='is_generated',
            field=models.BooleanField(default=False),
        ),
    ]
