# Generated by Django 6.0.2 on 2026-03-03 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_test_is_generated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='skill',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='core.skill'),
        ),
    ]
