# Generated by Django 6.0.2 on 2026-03-04 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='duration_minutes',
            field=models.IntegerField(default=60),
        ),
        migrations.AddField(
            model_name='test',
            name='scheduled_end',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='test',
            name='scheduled_start',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
